apiVersion: v1
kind: Service
metadata:
  name: promexporter
  labels:
    app: nginx-prometheus-exporter
spec:
  selector:
    app: nginx-prometheus-exporter
  ports:
  - protocol: TCP
    port: 9113
    targetPort: 9113

