apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
  labels:
    app: nginx-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter
    spec:
      containers:
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:1.1.0
        args:
        - -nginx.scrape-uri=http://nginx:8080/metrics
        ports:
        - containerPort: 9113
          name: metrics

