apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80 # listening port
      targetPort: 80 # expose inside the cluster
      nodePort: 30080 # expose outside the cluster
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30088
